### ISSUE TITLE
AddArray() does not respect initial capacity of Lists

### ISSUE THREAD

**Issue by floxay** [Scobalula/Cast.NET#1]
https://github.com/Scobalula/Cast.NET/blob/7cf3dac687047d5c843763abd448b5a7675efa7f/examples/Cast.NET.Example.GltfToCast/Program.cs#L71
_Based on the examples_ I expected AddArray() to use the instance which was passed in and that's why capacity is set, but that does not seem to be the case. Instead _it creates another instance with the same values/elements AND ignores capacity_, which makes me confused.

Is this the intended behavior of AddArray()?

I can see it being somewhat useful for non-empty Lists as a way to also implicitly Trim them but like in the example for empty ones specifying a capacity &mdash;if known&mdash; is I believe better to avoid resizing of the internal array.

**Comment by Scobalula** [comment]
Unfortunately this library is not receiving support and I will now archive it, unless Cast itself receives more support in general, consider this unsupported.
